spring.application.name=Payment-Service

server.port=8085

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.snzwjqihpdwvngaovedg
spring.datasource.password=Alitarek3102005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

Stripe.secretKey=sk_test_51TSe3YRwIS2892gyQalpCuHfbCOluDLSCzm1li4CY5YTan3TmOpL8bStbhkJdOWCC7oCQMnPilWoJaZPE0HakjMh0014BO545y
Stripe.publishableKey=pk_test_51TSe3YRwIS2892gyvBDUF8kHNu8XYgqki2o8wrIzGozzagnhOKZI0cTvaxxmguxhKmR0GqRevwsCIAiQ1VB9RzGS00kyAdkCKG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true




