spring.application.name=Payment-Service

server.port=8085

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.snzwjqihpdwvngaovedg
spring.datasource.password=Alitarek3102005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

Stripe.secretKey=sk_test_51TNLNVIo9lXCBIgWB4d5VCsyMWpbDrTOyPXlgsdCR6MXcTfREPeFgKunRa1dCWwwEgZ5bDRS3ELpc1WHJGnIzRpP00V7sl3V2O
Stripe.publishableKey=pk_test_51TNLNVIo9lXCBIgWfrG3somrVUgiuIFc3QK6ypmDIywo3GGE9ShScYPbqB2JnEGbNihLzJPtbupSsUDbZzVyFM0r00keFrx7sT

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true




