# Run the Eureka server on the standard port
server.port=8761

# Name the application
spring.application.name=discovery-server

# Eureka Server Configuration
eureka.instance.hostname=localhost
# Tell this app not to register with itself (because it is the server)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Disable the scary red text for local development
eureka.server.enable-self-preservation=false
# The URL where it hosts the registry
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/