spring.application.name=Cart-Service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8082
# EVERY SERVICE USES THIS EXACT FILE
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.snzwjqihpdwvngaovedg
spring.datasource.password=YourSuperSecretPassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true